### ISSUE TITLE
如果高亮的布局上有button 怎样去监听该button的点击事件

### ISSUE THREAD

**Issue by daiwenbo88** [hongyangAndroid/Highlight#35]
用户只能通过点击高亮布局上的button才能让高亮界面消失，不知道要怎样去监听这个button事件

**Comment by isanwenyu** [comment]
#36 已实现此功能 并且已经合并到主分支  请查看 `readme.md`
- 如果是点击事件 只需要在高亮布局中添加 `android:onClick="xxx"` 即可
- 如果是其他事件 也可以在`show()`调用之后 通过`getHightLightView()`得到高亮布局对象 然后查找自定义`button` 设置监听事件

**Comment by isanwenyu** [comment]
@hongyangAndroid 可以关闭这个问题了
